spring:
  application:
    name: myApp
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: ${spring.application.name}/api/v1/actuator/health
        healthCheckInterval: 20s
      config:
        enabled: true
      host: localhost
      port: 8500
    kubernets:
      config:
        name: generic-config